### ISSUE TITLE
Cyber Requirement set to None

### ISSUE THREAD

**Issue by MichaelDurlingGeneralElectric** [ge-high-assurance/VERDICT#36]
I was using the VERDICT MBAS tool and I had a Cyber Requirement Severity set to "None". The following file is a capture of the error message from the console.

[CyberRequirement set to None Error Message.txt](https://github.com/ge-high-assurance/VERDICT/files/4711659/CyberRequirement.set.to.None.Error.Message.txt)

**Comment by kityansiu** [comment]
[fixed](https://github.com/ge-high-assurance/VERDICT/commit/204eab0465a0c552b831c23cbd9397b022e93d75)
