### ISSUE TITLE
[Installation issue] requires 'osgi.bundle; org.eclipse.emf.mwe2.launch 0.0.0' but it could not be found 

### ISSUE THREAD

**Issue by cong-liu-2000** [ge-high-assurance/VERDICT#75]
Followed the installation steps till Step 6. 

6. Paste the following URL in the Work With: field and press the Enter key. Select the VERDICT for OSATE item and then clicking Next 
https://raw.githubusercontent.com/ge-high-assurance/VERDICT-update-sites/master/verdict-latest
-------------------------------------------------------------------------------------------------------------------
In the details window:

Cannot complete the install because one or more required items could not be found.
  Software being installed: DARPA CASE VERDICT Feature 1.0.0.202009042137 (com.ge.research.osate.verdict.feature.feature.group 1.0.0.202009042137)
  Missing requirement: com.ge.research.osate.verdict.dsl 1.0.0.202009042137 (com.ge.research.osate.verdict.dsl 1.0.0.202009042137) requires 'osgi.bundle; org.eclipse.emf.mwe2.launch 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: com.ge.research.osate.verdict 1.0.0.202009042137 (com.ge.research.osate.verdict 1.0.0.202009042137)
    To: osgi.bundle; com.ge.research.osate.verdict.dsl 0.0.0
  Cannot satisfy dependency:
    From: DARPA CASE VERDICT Feature 1.0.0.202009042137 (com.ge.research.osate.verdict.feature.feature.group 1.0.0.202009042137)
    To: org.eclipse.equinox.p2.iu; com.ge.research.osate.verdict [1.0.0.202009042137,1.0.0.202009042137]

**Comment by tuxji** [comment]
Are you using OSATE?  You must be using an Eclipse IDE that does not have the MWE2 Language SDK or MWE2 Runtime SDK installed.  These SDKs are available in Eclipse's standard update sites such as 2020-03, 2020-06, and Latest Eclipse Release.  You should be able to install these SDKs into your Eclipse IDE with these steps:

1. Run Help -> Install New Software...
2. Type "MWE" into the input text box containing the label "type filter text"
3. Select "--All Available Sites--" from the pulldown "type or select a site"
4. You should see "> [] Modeling" appear in the search results pane
5. Click on the ">" to expand what lies inside "Modeling"
6. You should see "MWE SDK", "MWE2 Language SDK", and/or "MWE2 Runtime SDK" as available choices
7. Select both "MWE2 Language SDK" and "MWE2 Runtime SDK"
8. Click on the Next button and keep going through the wizard until the SDKs are installed.
9. Restart your Eclipse IDE when prompted.

After installing these SDKs, you can try to install VERDICT again.  The first problem you saw should be fixed, although other problems may appear if you are not running the standard OSATE product.

**Comment by cong-liu-2000** [comment]
Yes. I am using OSATE 2.7.1.
When I type "MWE" in "type filter text", nothing shows up.
Is there a URL that I can enter in the "Work With" field?

**Comment by tuxji** [comment]
You can enter `http://download.eclipse.org/modeling/emft/mwe/updates/releases/2.11.1` in the "Work With" field.  Then you should see the MWE plugins.

Another way to check whether you have the MWE2 Launch plugin installed is to run Help -> About OSATE2, click the "Installation Details" button, click the "Plug-ins" tab, and type "mwe2" in the "type filter text" input text box.  In my OSATE 2.7.1, I will see four plugins with "mwe2" in their names:

```
	Eclipse Xtext	MWE2 Language	2.11.1.v20191121-1148	org.eclipse.emf.mwe2.language
	Eclipse Xtext	MWE2 Launch	2.11.1.v20191121-1148	org.eclipse.emf.mwe2.launch
	Eclipse Xtext	MWE2 Library	2.11.1.v20191121-1148	org.eclipse.emf.mwe2.lib
	Eclipse Xtext	MWE2 Runtime	2.11.1.v20191121-1148	org.eclipse.emf.mwe2.runtime
```

**Comment by cong-liu-2000** [comment]
It fixed the issue. It seems to be installed successfully. Thanks!
